### ISSUE TITLE
improve the save task button

### ISSUE THREAD

**Issue by prudhvir3ddy** [prudhvir3ddy/ToDoApp#16]
- increase save text and the right place to be able to click easily, use  default  text sizes

- once pressing enter on the task description  it should go to save button automatically add next  focus there

- write  it in as much less code as possible

**Comment by meetkparmar** [comment]
Hi @prudhvir3ddy, 

Can I work on this issue? 
Thanks in advance.

**Comment by prudhvir3ddy** [comment]
@meetkparmar yeah sure.

**Comment by meetkparmar** [comment]
Thanks, @prudhvir3ddy

But I get this error while run the project :
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 

Can you tell me how to solve this?

**Comment by prudhvir3ddy** [comment]
@meetkparmar add dummy file there or check the readme.md just now i added there.

**Comment by meetkparmar** [comment]
Sure, @prudhvir3ddy.
Thank you.

**Comment by meetkparmar** [comment]
1. "increase save text and the right place to be able to click easily, use default text sizes"
- I have updated text style to `TextAppearance.AppCompat.Large` instead of `TextAppearance.AppCompat.Small`.

2. "once pressing enter on the task description it should go to save button automatically add next focus there"
- Would you please explain, how exactly should UI behave in this case? @prudhvir3ddy

**Comment by prudhvir3ddy** [comment]
@meetkparmar what you suggested will work, why not medium over large ?

**Comment by meetkparmar** [comment]
- once pressing enter on the task description it should go to save button automatically add next focus there

[Screenrecorder-2020-05-04-19-00-31-823.mp4.zip](https://github.com/prudhvir3ddy/ToDoApp/files/4574925/Screenrecorder-2020-05-04-19-00-31-823.mp4.zip)

I share this video zip file. Check it out and if it is correct then I'll push the code.

**Comment by prudhvir3ddy** [comment]
@meetkparmar looking good. thanks. you can open the PR. i'll love to review it

**Comment by meetkparmar** [comment]
I have created the PR. Please review.

**Comment by meetkparmar** [comment]
Please review PR #28. @prudhvir3ddy
