### ISSUE TITLE
ignore signing the app if it's a PR.

### ISSUE THREAD

**Issue by prudhvir3ddy** [prudhvir3ddy/ToDoApp#25]
learn about github actions and [onpullrequest] use a different yml file and in that create unsigned release instead of signed release

**Comment by s-ayush2903** [comment]
Can't we handle it via making a new flavor for dev package?

**Comment by prudhvir3ddy** [comment]
@s-ayush2903 
even in that case i need to create different yml file and right now i am using app distribution, so i have to create multiple apps in firebase

**Comment by prudhvir3ddy** [comment]
also, dev env is needed when we have some external API. where we don't want to spoil the production db. right now app is working local.

i will take that issue once i complete the node.js part. thanks nice suggestion
